use std::io;
use rand::Rng;

fn os_random() {
    let random_number: u32 = rand::thread_rng().gen_range(1..=200);
    println!("The random number generated by OS is {random_number}");
}

fn guess() {
    println!("Guess your favourite number!!!::!!!)");
    let mut guess: String = String::new();
    // io::stdin().read_line(&mut guess).expect("Failed to read the message");
    io::stdin().read_line(&mut guess).unwrap();
    
    let guess: u32 = guess.trim().parse().expect("I'm expecting a number");

    println!("You guessed {guess}");
}



fn main() {
    println!("Welcome to Guess the Number Game::)");
    os_random();
    guess();
}
